### ISSUE TITLE
Build failure with ghc 8.4

### ISSUE THREAD

**Issue by DanBurton** [skogsbaer/xmlgen#7]
Add semigroup instances.
See also: https://ghc.haskell.org/trac/ghc/wiki/Migration/8.4#SemigroupMonoidsuperclasses

```
Building library for xmlgen-0.6.2.1..
[1 of 1] Compiling Text.XML.Generator ( src/Text/XML/Generator.hs, dist/build/Text/XML/Generator.o )

src/Text/XML/Generator.hs:281:10: error:
    • No instance for (Semigroup (Xml Attr))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Xml Attr)’
    |
281 | instance Monoid (Xml Attr) where
    |          ^^^^^^^^^^^^^^^^^

src/Text/XML/Generator.hs:375:10: error:
    • No instance for (Semigroup (Xml Elem))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Xml Elem)’
    |
375 | instance Monoid (Xml Elem) where
    |          ^^^^^^^^^^^^^^^^^

src/Text/XML/Generator.hs:566:13: error:
    • No instance for (Semigroup (Xml Attr)) arising from a use of ‘<>’
    • In the first argument of ‘(<#>)’, namely
        ‘xattr (T.pack "xml:lang") lang <> xattr (T.pack "lang") lang’
      In the third argument of ‘xelemQ’, namely
        ‘(xattr (T.pack "xml:lang") lang <> xattr (T.pack "lang") lang
            <#> children)’
      In the expression:
        xelemQ
          (namespace (T.pack "") (T.pack "http://www.w3.org/1999/xhtml"))
          (T.pack "html")
          (xattr (T.pack "xml:lang") lang <> xattr (T.pack "lang") lang
             <#> children)
    |
566 |            (xattr (T.pack "xml:lang") lang <>
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by peti** [comment]
Ping? This is issue is blocking several other builds with GHC 8.4.1, like `stack`.

**Comment by skogsbaer** [comment]
Thanks for the Ping @peti. I'll fix the problem asap.

**Comment by skogsbaer** [comment]
@peti This problem is fixed in 0.6.2.2 and in master.
@DanBurton what do I need to do to get xmlgen back into stackage?

**Comment by DanBurton** [comment]
@skogsbaer looks like `xmlgen` has already found its way back into stackage. In case it wasn't clear how: you get back in by opening a PR on https://github.com/fpco/stackage, as you would when adding a new one.
